2019-04-05 15:57:59,688 ERROR: Exception on / [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\base.html", line 39, in block "navbar"
    <li><a href="{{ url_for('Download/enterprise') }}">DOWNLOADS</a></li>
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'Download/enterprise'. Did you mean 'edit_profile' instead?
2019-04-05 15:58:36,245 INFO: MySQL startup [in C:\Users\User\PycharmProjects\MySQL\app\__init__.py:47]
2019-04-05 15:58:37,544 ERROR: Exception on / [GET] [in C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\MySQL\app\routes.py", line 22, in index
    return render_template('index.html', title='Home')
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\User\PycharmProjects\MySQL\app\templates\base.html", line 39, in block "navbar"
    <li><a href="{{ url_for('download') }}">DOWNLOADS</a></li>
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "C:\Users\User\PycharmProjects\MySQL\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'download'. Did you mean 'follow' instead?
