2019-03-19 23:33:00,282 ERROR: Exception on / [GET] [in C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\routes.py", line 41, in index
    prev_url=prev_url)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\base.html", line 1, in top-level template code
    {% extends 'css/base.html' %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: css/base.html
2019-03-19 23:33:00,691 ERROR: Exception on / [GET] [in C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\routes.py", line 41, in index
    prev_url=prev_url)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\base.html", line 1, in top-level template code
    {% extends 'css/base.html' %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: css/base.html
2019-03-19 23:33:00,818 ERROR: Exception on / [GET] [in C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\routes.py", line 41, in index
    prev_url=prev_url)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\app\templates\base.html", line 1, in top-level template code
    {% extends 'css/base.html' %}
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\KaiJor\PycharmProjects\EA_MySQL\venv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: css/base.html
